const KEY='cozy-ledger-v5';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,10); const today=()=>new Date().toISOString().slice(0,10);
const money=n=>(Number(n)||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
const dparse=s=>new Date((s||today())+'T12:00:00'); const iso=d=>d.toISOString().slice(0,10); const addDays=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
const base={theme:'cozy',lookAheadDays:30,aiEndpoint:'',history:[],lastDeleted:null,accounts:[{id:uid(),name:'Checking',amount:0,type:'checking',status:'active'},{id:uid(),name:'Safe to Spend',amount:0,type:'safe',status:'active'}],bills:[{id:uid(),name:'Mortgage',amount:0,date:today(),recurring:'monthly',status:'planned',funded:0,category:'fixed'}],buckets:[{id:uid(),name:'Groceries',amount:250,date:today(),recurring:'none',status:'planned',category:'variable'},{id:uid(),name:'Gas',amount:150,date:today(),recurring:'none',status:'planned',category:'variable'}],paychecks:[{id:uid(),name:'Nick Paycheck',amount:0,date:today(),recurring:'biweekly',status:'planned',category:'income'},{id:uid(),name:'Danielle Paycheck',amount:0,date:iso(addDays(new Date(),7)),recurring:'biweekly',status:'planned',category:'income'}],goals:[{id:uid(),name:'Emergency Fund',amount:100,date:'',recurring:'none',status:'planned',target:10000,current:0,category:'savings'}],events:[],archives:[]};
let state=load(), cal=new Date();
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return {...structuredClone(base),...s,history:s.history||[],archives:s.archives||[]}}catch{return structuredClone(base)}}
function persist(msg='Saved'){localStorage.setItem(KEY,JSON.stringify(state));render();toast(msg)}
function log(msg){state.history.unshift({id:uid(),date:new Date().toLocaleString(),msg});state.history=state.history.slice(0,80)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function active(arr){return arr.filter(x=>x.status!=='archived')}
function totalAccounts(){return active(state.accounts).reduce((s,x)=>s+Number(x.amount||0),0)}
function nextDate(d,rec){const x=new Date(d); if(rec==='weekly')x.setDate(x.getDate()+7); else if(rec==='biweekly')x.setDate(x.getDate()+14); else if(rec==='monthly')x.setMonth(x.getMonth()+1); else x.setFullYear(x.getFullYear()+99); return x}
function expand(items,start,end){const out=[]; for(const item of active(items)){let d=dparse(item.date); if(!item.date) continue; if(item.recurring==='none'||!item.recurring){if(d>=start&&d<=end)out.push({...item,occurrenceDate:iso(d)});continue} let guard=0; while(d<start&&guard++<100)d=nextDate(d,item.recurring); while(d<=end&&guard++<200){out.push({...item,occurrenceDate:iso(d)});d=nextDate(d,item.recurring)}} return out}
function getPlan(days=state.lookAheadDays){const start=dparse(today()), end=addDays(start,Number(days)||30); const pay=expand(state.paychecks,start,end).sort((a,b)=>a.occurrenceDate.localeCompare(b.occurrenceDate)); const bills=expand(state.bills,start,end).sort((a,b)=>a.occurrenceDate.localeCompare(b.occurrenceDate)); let available=totalAccounts(); const lines=[]; pay.forEach(x=>{available+=Number(x.amount);lines.push({...x,type:'income',delta:Number(x.amount),date:x.occurrenceDate})}); bills.forEach(x=>{if(x.status==='paid')return; available-=Number(x.amount);lines.push({...x,type:'fixed',delta:-Number(x.amount),date:x.occurrenceDate})}); active(state.buckets).forEach(x=>{available-=Number(x.amount);lines.push({...x,type:'variable',delta:-Number(x.amount),date:'Resets this period'})}); active(state.goals).forEach(x=>{available-=Number(x.amount);lines.push({...x,type:'savings',delta:-Number(x.amount),date:x.date||'Goal'})}); lines.push({id:'safe',name:'Safe to Spend',type:'safe',delta:available,date:'After allocations',status:'planned'}); return {available,lines,income:pay.reduce((s,x)=>s+Number(x.amount),0),bills:bills.reduce((s,x)=>s+(x.status==='paid'?0:Number(x.amount)),0),variable:active(state.buckets).reduce((s,x)=>s+Number(x.amount),0),savings:active(state.goals).reduce((s,x)=>s+Number(x.amount),0)}}
function fundedThrough(){const start=dparse(today()); for(let i=1;i<=120;i++){if(getPlan(i).available<0)return iso(addDays(start,i-1));} return iso(addDays(start,120))}
function setScreen(id){$$('.navbtn,.screen').forEach(x=>x.classList.remove('active')); const b=document.querySelector(`[data-screen="${id}"]`); if(b&&b.classList.contains('navbtn'))b.classList.add('active'); $('#'+id).classList.add('active'); closeDrawer(); render();}
function openDrawer(){ $('#drawer').classList.add('open'); $('#overlay').classList.add('open')} function closeDrawer(){ $('#drawer').classList.remove('open'); $('#overlay').classList.remove('open')}
$$('[data-screen]').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen)); $('#menuBtn').onclick=openDrawer; $('#closeDrawer').onclick=closeDrawer; $('#overlay').onclick=closeDrawer;
function render(){document.documentElement.dataset.theme=state.theme==='cozy'?'':state.theme; $('#heroSafe').textContent=money(getPlan().available); renderDashboard();renderAccounts();renderCrud('bills','Bills','bill');renderCrud('buckets','Buckets','bucket');renderCrud('paychecks','Paychecks','paycheck');renderCalendar();renderGameplan();renderAssign();renderAfford();renderInbox();renderHistory();renderAI();renderSettings();}
function panel(t,b){return `<div class="panel"><h2>${t}</h2>${b}</div>`}
function metric(t,v){return `<div class="metric"><span>${t}</span><strong>${v}</strong></div>`}
function renderDashboard(){const p=getPlan(); const runway=fundedThrough(); $('#dashboard').innerHTML=panel('Household Snapshot',`<div class="grid">${metric('Current balances',money(totalAccounts()))}${metric('Expected income',money(p.income))}${metric('Funded through',runway)}${metric('Safe to spend',money(p.available))}</div>`)+panel('Today’s Financial Mission',missionHTML())}
function missionHTML(){const tasks=[['Update account balances','accounts'],['Check Financial Inbox','inbox'],['Review Game Plan','gameplan'],['Export backup after big changes','settings']];return tasks.map(([t,s],i)=>`<div class="row"><div><strong>${i+1}. ${t}</strong><br><small>Tap to continue</small></div><button class="ghost mini" onclick="setScreen('${s}')">Open</button></div>`).join('')}
function renderAccounts(){const rows=active(state.accounts).map(x=>itemRow('accounts',x,`${x.type||'account'} • ${x.status||'active'}`)).join('')||empty('No accounts yet.','Add Account','account'); $('#accounts').innerHTML=panel('Accounts',`<button class="primary" onclick="openItem('account')">Add Account</button>${rows}`)}
function renderCrud(key,title,type){const rows=active(state[key]).map(x=>itemRow(key,x,`${x.date||'No date'} • ${x.recurring||'none'} • ${x.status||'planned'}`)).join('')||empty(`No ${title.toLowerCase()} yet.`,`Add ${title.slice(0,-1)}`,type); $('#'+key).innerHTML=panel(title,`<div class="form-grid"><button class="primary" onclick="openItem('${type}')">Add ${title.slice(0,-1)}</button><input placeholder="Search ${title}" oninput="filterRows(this.value,'${key}')"><select onchange="sortList('${key}',this.value)"><option value="date">Sort by date</option><option value="amount">Sort by amount</option><option value="name">Sort by name</option></select></div><div id="${key}Rows">${rows}</div>`) }
function empty(text,label,type){return `<div class="empty">${text}<br><br><button class="primary" onclick="openItem('${type}')">${label}</button></div>`}
function itemRow(key,x,meta){let prog=''; if(key==='bills'){const pct=Math.min(100,(Number(x.funded||0)/Math.max(1,Number(x.amount||0)))*100); prog=`<div class="progress"><div style="width:${pct}%"></div></div><small>${money(x.funded||0)} funded of ${money(x.amount)}</small>`} return `<div class="row item-row" data-name="${x.name.toLowerCase()}"><div><strong>${x.name}</strong><br><small>${meta}</small>${prog}</div><div><strong>${money(x.amount)}</strong><br><div class="actions"><button class="ghost mini" onclick="openItem('${keyToType(key)}','${x.id}')">Edit</button><button class="ghost mini" onclick="quickStatus('${key}','${x.id}')">Status</button><button class="ghost mini" onclick="archiveItem('${key}','${x.id}')">Archive</button><button class="danger mini" onclick="deleteItem('${key}','${x.id}')">Delete</button></div></div></div>`}
function keyToType(k){return {accounts:'account',bills:'bill',buckets:'bucket',paychecks:'paycheck',goals:'goal',events:'event'}[k]||k}
function typeToKey(t){return {account:'accounts',bill:'bills',bucket:'buckets',paycheck:'paychecks',goal:'goals',event:'events'}[t]}
function filterRows(q,key){q=q.toLowerCase();$$(`#${key}Rows .item-row`).forEach(r=>r.style.display=r.dataset.name.includes(q)?'flex':'none')}
function sortList(key,by){state[key].sort((a,b)=>by==='amount'?Number(b.amount)-Number(a.amount):(a[by]||'').localeCompare(b[by]||''));persist('Sorted')}
function quickStatus(key,id){const x=state[key].find(i=>i.id===id); const opts=key==='paychecks'?['planned','received','archived']:key==='bills'?['planned','funded','paid','archived']:['planned','active','archived']; const next=prompt(`Set status for ${x.name}: ${opts.join(', ')}`,x.status||opts[0]); if(!next)return; x.status=next; if(key==='paychecks'&&next==='received')log(`${x.name} marked received (${money(x.amount)})`); if(key==='bills'&&next==='paid')log(`${x.name} marked paid (${money(x.amount)})`); persist('Status updated')}
function archiveItem(key,id){const x=state[key].find(i=>i.id===id); if(!x)return; x.status='archived'; state.archives.unshift({...x,archivedFrom:key,archivedAt:new Date().toLocaleString()}); log(`${x.name} archived`); persist('Archived')}
function deleteItem(key,id){const x=state[key].find(i=>i.id===id); if(!x||!confirm(`Delete ${x.name}? This can be undone briefly from the confirmation.`))return; state.lastDeleted={key,item:x}; state[key]=state[key].filter(i=>i.id!==id); log(`${x.name} deleted`); localStorage.setItem(KEY,JSON.stringify(state)); render(); const t=$('#toast'); t.innerHTML=`Deleted ${x.name}. <button onclick="undoDelete()">Undo</button>`; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),7000)}
function undoDelete(){const d=state.lastDeleted;if(!d)return;state[d.key].push(d.item);log(`${d.item.name} restored`);state.lastDeleted=null;persist('Restored')}
function renderCalendar(){const y=cal.getFullYear(),m=cal.getMonth();const first=new Date(y,m,1),last=new Date(y,m+1,0),start=addDays(first,-first.getDay()),end=addDays(last,6-last.getDay());let events=[];expand(state.bills,start,end).forEach(x=>events.push({...x,kind:'fixed',date:x.occurrenceDate}));expand(state.paychecks,start,end).forEach(x=>events.push({...x,kind:'income',date:x.occurrenceDate}));active(state.events).forEach(x=>events.push({...x,kind:'event'}));active(state.goals).filter(x=>x.date).forEach(x=>events.push({...x,kind:'savings'}));let cells=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="day-name">${d}</div>`).join('');for(let d=new Date(start);d<=end;d=addDays(d,1)){const day=iso(d),ev=events.filter(e=>e.date===day);cells+=`<div class="day ${d.getMonth()!==m?'out':''}" onclick="openItem('event','', '${day}')"><strong>${d.getDate()}</strong>${ev.map(e=>`<span class="pill ${e.kind}">${e.name} ${money(e.amount)}</span>`).join('')}</div>`}const monthIncome=events.filter(e=>e.kind==='income').reduce((s,e)=>s+Number(e.amount),0),monthBills=events.filter(e=>e.kind==='fixed').reduce((s,e)=>s+Number(e.amount),0);$('#calendar').innerHTML=panel('Calendar',`<div class="calendar-head"><button class="ghost" onclick="cal.setMonth(cal.getMonth()-1);renderCalendar()">←</button><h3>${cal.toLocaleString(undefined,{month:'long',year:'numeric'})}</h3><button class="ghost" onclick="cal.setMonth(cal.getMonth()+1);renderCalendar()">→</button></div><div class="actions"><button class="primary mini" onclick="openItem('bill')">Add Bill</button><button class="primary mini" onclick="openItem('paycheck')">Add Paycheck</button><button class="primary mini" onclick="openItem('goal')">Add Goal</button><button class="primary mini" onclick="openItem('event')">Add Event</button></div><div class="calendar">${cells}</div><div class="grid"><div class="metric"><span>Month income</span><strong>${money(monthIncome)}</strong></div><div class="metric"><span>Month fixed bills</span><strong>${money(monthBills)}</strong></div></div>`)}
function renderGameplan(){const p=getPlan();$('#gameplan').innerHTML=panel('Game Plan',`<div class="form-grid"><label>Days to look ahead<input id="days" type="number" value="${state.lookAheadDays}"></label><button class="primary" onclick="state.lookAheadDays=Number($('#days').value||30);log('Game plan generated for '+state.lookAheadDays+' days');persist('Plan generated')">Generate</button></div><p class="muted">Priority: fixed bills → variable buckets → savings goals → safe-to-spend.</p>`)+panel('Allocation',p.lines.map(x=>`<div class="row"><div><strong>${x.name}</strong><br><small>${x.date||''} • ${x.type||''}</small></div><strong>${x.delta>=0?'+':''}${money(x.delta)}</strong></div>`).join(''))}
function renderAssign(){const p=getPlan();const root=totalAccounts()+p.income;$('#assign').innerHTML=panel('Assign Money Visual',`<div class="flow-root">Current balances + expected paychecks = ${money(root)}</div>${p.lines.filter(x=>x.type!=='income').map(x=>`<div class="flow-item"><strong>${x.name}</strong><br><small>${x.type} • ${x.date}</small><div class="progress"><div style="width:${Math.min(100,Math.abs(x.delta)/Math.max(1,root)*100)}%"></div></div><strong>${money(x.delta)}</strong></div>`).join('')}`)}
function renderAfford(){const p=getPlan();$('#afford').innerHTML=panel('Can We Afford It?',`<div class="form-grid"><label>Purchase name<input id="buyName" placeholder="Guitar, trip, furniture..."></label><label>Cost<input id="buyCost" type="number" step="0.01"></label><button class="primary" onclick="affordCheck()">Check</button></div><div id="affordOut" class="ai-box">Enter a purchase to simulate the impact.</div>`) }
function affordCheck(){const cost=Number($('#buyCost').value||0),name=$('#buyName').value||'Purchase',before=getPlan().available,after=before-cost; $('#affordOut').textContent=`${name}\nBefore safe-to-spend: ${money(before)}\nAfter purchase: ${money(after)}\n\n${after>=0?'🟢 Looks safe in this plan window.':'🔴 This would create a shortfall in this plan window.'}`}
function renderInbox(){const p=getPlan();const warnings=[];if(p.available<0)warnings.push(`Projected shortfall of ${money(Math.abs(p.available))}.`);expand(state.bills,dparse(today()),addDays(new Date(),7)).forEach(b=>warnings.push(`${b.name} due within 7 days: ${money(b.amount)}.`));if(!warnings.length)warnings.push('No urgent items right now.');$('#inbox').innerHTML=panel('Financial Inbox',warnings.map(w=>`<div class="row"><strong>⚠️ ${w}</strong></div>`).join(''))}
function renderHistory(){const archiveRows=state.archives.slice(0,20).map(x=>`<div class="row"><div><strong>${x.name}</strong><br><small>${x.archivedFrom} • ${x.archivedAt}</small></div><span>${money(x.amount)}</span></div>`).join('')||'<p class="muted">No archived items yet.</p>';$('#history').innerHTML=panel('What Changed?',(state.history.length?state.history.map(h=>`<div class="row"><div><strong>${h.msg}</strong><br><small>${h.date}</small></div></div>`).join(''):'<p class="muted">No changes logged yet.</p>'))+panel('Archived Items',archiveRows)}
function localSummary(){const p=getPlan();return `Quick Read\nYou are funded through ${fundedThrough()}. Estimated safe-to-spend after ${state.lookAheadDays} days is ${money(p.available)}.\n\nCovered\nExpected income: ${money(p.income)}\nFixed bills: ${money(p.bills)}\nVariable buckets: ${money(p.variable)}\nSavings goals: ${money(p.savings)}\n\nWatch-outs\n${p.available<0?'Projected shortfall detected.':'No shortfall detected in this plan window.'}`}
function renderAI(){ $('#ai').innerHTML=panel('AI Guide',`<p class="muted">Use local summary now, or paste a secure AI proxy endpoint later. Never put an API key directly in GitHub Pages.</p><label>AI Proxy Endpoint<input id="aiEndpoint" value="${state.aiEndpoint||''}"></label><div class="actions"><button class="primary" onclick="state.aiEndpoint=$('#aiEndpoint').value;persist('AI endpoint saved')">Save Endpoint</button><button class="ghost" onclick="$('#aiOut').textContent=localSummary()">Local Summary</button><button class="primary" onclick="callAI()">Ask AI</button></div><div id="aiOut" class="ai-box">${localSummary()}</div>`) }
async function callAI(){const out=$('#aiOut'); if(!state.aiEndpoint){out.textContent='AI unavailable. Using local summary instead.\n\n'+localSummary();return} try{out.textContent='Asking AI...';const r=await fetch(state.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,plan:getPlan()})});const j=await r.json();out.textContent=j.summary||j.output||JSON.stringify(j,null,2)}catch(e){out.textContent='AI unavailable. Using local summary instead.\n\n'+localSummary()}}
function renderSettings(){ $('#settings').innerHTML=panel('Settings',`<label>Theme<select onchange="state.theme=this.value;persist('Theme saved')"><option value="cozy" ${state.theme==='cozy'?'selected':''}>Cozy Ledger</option><option value="classic" ${state.theme==='classic'?'selected':''}>Classic</option><option value="dark" ${state.theme==='dark'?'selected':''}>Dark Mode</option></select></label><div class="actions"><button class="primary" onclick="exportBackup()">Export Backup</button><label class="ghost">Import Backup<input type="file" accept="application/json" style="display:none" onchange="importBackup(event)"></label><button class="ghost" onclick="dailyBackup()">Create Daily Backup</button><button class="danger" onclick="resetApp()">Reset App</button></div><p class="muted">Backups include all active, archived, and history data.</p>`) }
function openItem(type,id='',presetDate=''){const key=typeToKey(type);const item=id?state[key].find(x=>x.id===id):{};mType.value=type;mId.value=id;mName.value=item.name||'';mAmount.value=item.amount||0;mDate.value=presetDate||item.date||today();mRecurring.value=item.recurring||'none';mStatus.value=item.status||'planned';deleteBtn.style.display=id?'inline-block':'none';modalTitle.textContent=(id?'Edit ':'Add ')+type;modal.showModal()}
modalForm.onsubmit=e=>{e.preventDefault();const type=mType.value,key=typeToKey(type),id=mId.value;let obj={id:id||uid(),name:mName.value,amount:Number(mAmount.value||0),date:mDate.value,recurring:mRecurring.value,status:mStatus.value,category:type==='paycheck'?'income':type==='bucket'?'variable':type==='goal'?'savings':type==='event'?'event':'fixed'};if(key==='bills')obj.funded=state[key].find(x=>x.id===id)?.funded||0;const i=state[key].findIndex(x=>x.id===id);if(i>=0){state[key][i]={...state[key][i],...obj};log(`${obj.name} updated`)}else{state[key].push(obj);log(`${obj.name} added`)}modal.close();persist('Saved')}
deleteBtn.onclick=()=>{modal.close();deleteItem(typeToKey(mType.value),mId.value)};

function asArray(v){return Array.isArray(v)?v:[]}
function normalizeItem(x={}, fallbackCategory='fixed'){
  const amount = x.amount ?? x.balance ?? x.value ?? 0;
  const date = x.date ?? x.dueDate ?? x.nextDate ?? x.targetDate ?? '';
  const status = x.status || (x.archived ? 'archived' : 'planned');
  return {
    ...x,
    id: x.id || uid(),
    name: x.name || x.title || 'Imported Item',
    amount: Number(amount)||0,
    date: date || today(),
    recurring: x.recurring || x.frequency || 'none',
    status,
    category: x.category || x.type || fallbackCategory
  }
}
function normalizeBackup(raw){
  // Accept v5 backups, older Cozy Ledger backups, and daily backup wrappers.
  let src = raw?.data && raw?.createdAt ? raw.data : raw;
  if(src?.state) src = src.state;
  if(src?.settings && typeof src.settings === 'object') src = {...src, ...src.settings};
  const next = structuredClone(base);
  next.theme = src.theme || src.settings?.theme || next.theme;
  next.lookAheadDays = Number(src.lookAheadDays || src.settings?.lookAheadDays || next.lookAheadDays) || 30;
  next.aiEndpoint = src.aiEndpoint || src.settings?.aiEndpoint || '';
  next.history = asArray(src.history);
  next.archives = asArray(src.archives);
  next.lastDeleted = src.lastDeleted || null;
  next.accounts = asArray(src.accounts).map(x=>normalizeItem(x,'account'));
  next.bills = asArray(src.bills).map(x=>normalizeItem(x,'fixed'));
  next.buckets = asArray(src.buckets).map(x=>normalizeItem(x,'variable'));
  next.paychecks = asArray(src.paychecks).map(x=>normalizeItem(x,'income'));
  next.goals = asArray(src.goals).map(x=>({...normalizeItem(x,'savings'), target:Number(x.target||0), current:Number(x.current||0)}));
  next.events = [...asArray(src.events), ...asArray(src.customEvents)].map(x=>normalizeItem(x,'event'));
  // Avoid a blank app if an older backup was missing a section.
  if(!next.accounts.length) next.accounts = structuredClone(base.accounts);
  if(!next.bills.length) next.bills = [];
  if(!next.buckets.length) next.buckets = [];
  if(!next.paychecks.length) next.paychecks = [];
  if(!next.goals.length) next.goals = [];
  return next;
}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cozy-ledger-v5-backup-${today()}.json`;a.click();log('Backup exported');persist('Backup exported')}
function dailyBackup(){state.dailyBackup={createdAt:new Date().toLocaleString(),data:JSON.parse(JSON.stringify(state))};log('Daily backup created');persist('Daily backup created')}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const raw=JSON.parse(r.result);state=normalizeBackup(raw);log('Backup imported');persist('Backup imported')}catch(err){console.error(err);alert('Could not import backup. Make sure you selected a Cozy Ledger JSON backup file.')}};r.readAsText(f); e.target.value=''}
function resetApp(){if(confirm('Reset all app data? Export a backup first.')){state=structuredClone(base);persist('Reset complete')}}
render();
